@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yzg0MmViZDQ5MmE3MzQ2YzRhNDQwNyIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiYWNjb3VudFR5cGUiOiJhZG1pbiIsImlhdCI6MTc0MTg0NTgxNywiZXhwIjoxNzQxODQ5NDE3fQ.bqk10Ps4M41eqhUdFJKyGvIU9amN2iIb-vR8gxLM3eA
GET {{host}}/admin/find

### Admin Login
# Get a token from the endpoint as login
# Parameter: { email: string, password: string }
# Response: { message: string, token: string}
# Content-Type: application/json
POST {{host}}/a2kstaffs/login/admin
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "12345678"
}


###
GET {{host}}/admin/accounts
Authorization: Bearer {{token}}

###
GET {{host}}/admin/accounts/intern-request
Authorization: Bearer {{token}}