@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzlhMmQ5ZDA4NjhlZDFlZWQzNTljZCIsImVtYWlsIjoic3VwZXJ2aXNvckBzdXBlcnZpc29yLmNvbSIsImFjY291bnRUeXBlIjoic3VwZXJ2aXNvciIsImlhdCI6MTc0MTMxNjE2OSwiZXhwIjoxNzQxMzE5NzY5fQ.gCmbvMj2JRcVkpTLe7MqpDo0qHr0M4PY3pZ_yGlPg4E
### Setup
### Login as supervisor
# Returns a token
POST {{host}}/auth/login/supervisor
Content-Type: application/json

{
    "email": "supervisor@supervisor.com",
    "password": "12345678"
}

#  Sample Response
# {
#   "message": "Login Successful",
#   "token": "A string"
# }



### Get all existing supervisors
# Get an array of tasks assigned to intern
# add the internId as a query parameter
# Response: { departments: objects[]}
GET {{host}}/supervisors/all
Authorization: Bearer {{token}}

### Register a supervisor account
# The new user is returned
POST {{host}}/supervisors/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "foo", 
    "lastName": "bar", 
    "age": 30,
    "email": "supervisorssssss@susosrss.com",
    "password": "12345678",
    "department": "IT"
}
###
# Sample response
{
  "firstName": "foo",
  "lastName": "bar",
  "age": 30,
  "email": "supervisorsssss@supervisorss.com",
  "assignedInterns": [],
  "department": "67c9a564d9a683703619e4b4",
  "accountType": "supervisor",
  "_id": "67c9a565d9a683703619e4b6"
}

