@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Yzg0MmViZDQ5MmE3MzQ2YzRhNDQwNyIsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiYWNjb3VudFR5cGUiOiJhZG1pbiIsImlhdCI6MTc0MTMwODAyNSwiZXhwIjoxNzQxMzExNjI1fQ.T6yPG7cimpYE8Q-DMsB1lGENB92JuzDbdrSxvOdmzVY
### Setup
# Get a token first
POST {{host}}/auth/login/admin
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "12345678"
}

### Get all existing supervisors
# Get an array of tasks assigned to intern
# add the internId as a query parameter
# Response: { departments: objects[]}
GET {{host}}/supervisors/all
Authorization: Bearer {{token}}

### Register a supervisor account
# The new user is returned
POST {{host}}/supervisors/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "foo", 
    "lastName": "bar", 
    "age": 30,
    "email": "supervisorssssss@susosrss.com",
    "password": "12345678",
    "department": "IT"
}
###
# Sample response
{
  "firstName": "foo",
  "lastName": "bar",
  "age": 30,
  "email": "supervisorsssss@supervisorss.com",
  "assignedInterns": [],
  "department": "67c9a564d9a683703619e4b4",
  "accountType": "supervisor",
  "_id": "67c9a565d9a683703619e4b6"
}

