@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2E4OTJhY2Q0ODk5OTc4ZDFiNjY2NiIsImVtYWlsIjoic3VwQHN1cC5jb20iLCJhY2NvdW50VHlwZSI6InN1cGVydmlzb3IiLCJpYXQiOjE3NDE1NzI0MjIsImV4cCI6MTc0MTU3NjAyMn0.vXn_paQ48WHRLdm6LdJA4HidoOHCvLCciB2psCgVT_c
### Setup
# Get a token first
POST {{host}}/auth/login/supervisor
Content-Type: application/json

{
    "email": "sup@sup.com",
    "password": "12345678"
}

### Find all tasks assigned to Intern
# Get an array of tasks assigned to intern
# add the internId as a query parameter
# Response: { tasks: objects[]}
# 
GET {{host}}/tasks/intern?internId=67cbecaa3f611eedb0b953f0
Authorization: Bearer {{token}}

###
POST {{host}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Foo",
    "description": "Foo",
    "deadline": "2025-03-10 02:08:44",
    "assignedInterns" : "67cbecaa3f611eedb0b953ef"
}




